using System.Text.Json;

/// <summary>JSON helper methods for request processing.</summary>
namespace MinimalApi;

internal partial class Helper
{
    /// <summary>Deserializes JSON request body with error handling.</summary>
    /// <typeparam name="T">Target deserialization type.</typeparam>
    /// <param name="request">HTTP request with JSON body.</param>
    /// <returns>Deserialized object or error result.</returns>
    /// <remarks>helper method below was generated by AI - DeepSeek to capture
    /// malformed JSON.</remarks>
    public static async Task<(T? value, IResult? error)> TryReadJsonBodyAsync<T>
        (HttpRequest request)
    {
        try
        {
            request.EnableBuffering();
            using StreamReader sr = new(request.Body, leaveOpen: true);
            string body = await sr.ReadToEndAsync();
            request.Body.Position = 0;

            if (string.IsNullOrWhiteSpace(body))
                return (default, BadRequest("Request body is empty"));

            JsonSerializerOptions options = new()
            {
                PropertyNameCaseInsensitive = true
            };

            try
            {
                T? obj = JsonSerializer.Deserialize<T>(body, options);
                if (obj == null) return (default, BadRequest("Unable to parse JSON body"));
                return (obj, null);
            }
            catch (JsonException jex)
            {
                WriteLine($"\nMalformed JSON: {jex.Message}");
                return (default, BadRequest("Malformed JSON in request body"));
            }
            catch (Exception ex)
            {
                WriteLine($"\nUnexpected error deserializing JSON: {ex.Message}");
                return (default, BadRequest("Invalid JSON in request body"));
            }
        }
        catch (Exception ex)
        {
            WriteLine($"\nError reading request body: {ex.Message}");
            return (default, BadRequest("Unable to read request body"));
        }
    }
}